### ISSUE TITLE
Redirect back to public page

### ISSUE THREAD

**Issue by npodonnell** [ivandotv/nextjs-client-signin-logic#37]
Hello Ivan

I found this package very useful and integrated it into my application. Very nice work :)

I had one small issue: If I'm on a public page then sign-in, I'm not returned back to that page. It only works for private pages. I fixed this by wrapping all pages in `<AuthGuard>` regardless of whether they're public or private, then in AuthGuard.tsx I changed the `useEffect` function to look like this:

```typescript
    useEffect(() => {
        if (!initializing) {
            //auth is initialized and there is no user
            if (!user) {
                if (!skipRedirect) {
                    // Set redirect unless it's a special route
                    // for which it should be skipped.
                    setRedirect(router.route)
                }
                if (requireAuth) {
                    router.push("/signin")      
                }
            }
        }
    }, [initializing, router, user, setRedirect])
```

This requires an extra property for the page called `skipRedirect`, which doesn't need to be set except for pages which you don't want to redirect back to ― such as the sign-in page.

I haven't got time to do a PR but I think this would be a nice addition.

**Comment by raja-poudel** [comment]
@npodonnell I have created PR related to this issue.

**Comment by ivandotv** [comment]
closed via https://github.com/ivandotv/nextjs-client-signin-logic/commit/be550224523fb63c04b9eba2cba0da080e9b7a60

**Comment by npodonnell** [comment]
> 



> l I have created PR related to this issue.

Thank you! Your solution is simpler and more genius than mine.
